# Generated by Django 5.0 on 2023-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_asset_assetrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="AssetRequest",
        ),
    ]
