# Generated by Django 5.0 on 2023-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_hostel_remove_asset_quantity_alter_asset_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hostel",
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
